### ISSUE TITLE
Built-in schemas

### ISSUE THREAD

**Issue by cafca** [p2panda/design-document#11]
I want to write something about built-in schemas. Which ones do we have?

### `schema` 
describes schemas

fields:
* name
* description
* fields (list of field definitions)

### `persona`

fields:
* username
* relations (list of relations to other personas, e.g. "same user as..." / same-as or "bot controlled by...")

**Comment by adzialocha** [comment]
Really like the name and definition of `persona`, it fits very well :+1: 

I wouldn't add "profile picture" fields to `persona`, as this can be seen as a more "application" concern than a protocol concern, and would fit better in a user log than a system log.

`schema` schemas have been defined here so far: https://github.com/p2panda/design-document/blob/master/spec/server-client/schemas.md where I can see a `version` field as well. Also I wonder if we should already reflect migrations in the `schema` schema?
