### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by TimGuenther** [p2panda/design-document#2]
Hi,

What is the status of the project? Is it still planned to implement it? 
I'm currently brain storming about a similar project with a slight different scope. I would like to have a tool for everyday use. 

See an draft version/writeup here: https://github.com/shared-economy/share-your-stuff-api/blob/master/README.md

**Comment by adzialocha** [comment]
Hi! Very cool! Thank you for sharing! This looks similar to what we do, but more sophisticated when it comes to managing resources.

We had a couple of meetings with people in the last weeks and start to form a small team around p2panda development. I will start a group soon with more updates and ways to contribute to the project, but yes: we are ready for implementation (based on the SSB protocol) :-)

**Comment by TimGuenther** [comment]
Nice. I'm looking forward to see the progress.

**Comment by adzialocha** [comment]
@TimGuenther, I just updated some documents and uploaded the last meeting protocols around p2panda, you can find them here: https://wolke.liebechaos.org/s/nN9Waf5sHB2dFzw

I will soon make sure this is more accessible for others, but for now this is the link :smile_cat:

**Comment by TimGuenther** [comment]
Thanks will have a look in the evening.

**Comment by adzialocha** [comment]
I've linked the meeting minutes now to our README.md document :+1: also there is a chat channel now on https://wald.liebechaos.org :smile:
